### ISSUE TITLE
language server will not start - macOS 10.14.3

### ISSUE THREAD

**Issue by synaptis** [lingua-pupuli/puppet-editor-services#113] opened 2019-01-25 02:26 UTC
### What Versions are you running?

OS Version: macOC Mojave 10.14.3
VSCode Version: 1.28 -> 1.30
Puppet Extension Version: 0.13.0 -> 0.15.1
Puppet Agent Version: N/A
PDK Version (if applicable): 1.7 -> 1.8

### What You Are Seeing?
Langauge server will not start. This occurs across multiple versions of PDK and multiple versions of the extention. Extention versions >0.14.0 produce these errors:

> System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- puppet (LoadError)
> 	from System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
> 	from /Users/ez002260/.vscode/extensions/jpogran.puppet-vscode-0.15.0/vendor/languageserver/lib/puppet_languageserver.rb:7:in '<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
> 	from /Users/ez002260/.vscode/extensions/jpogran.puppet-vscode-0.15.0/vendor/languageserver/puppet-languageserver:8:in '<main>'

Extention versions 0.14.0 and below produce these errors:

> [Error - 10:14:54 AM] Connection to server is erroring. Shutting down server.
> [Error - 10:14:54 AM] Connection to server is erroring. Shutting down server.

### What is Expected?

That the language server starts.

### How Did You Get This To Happen? (Steps to Reproduce)

Attempting to set up a Puppet dev environment on macOS. We saw similar issues on Windows 10 but the combination of VSCode 1.30.2, PDK 1.7.0 and Extention 0.14.0 worked there.

**Comment by glennsarti** [comment] 2019-05-27 02:17
I suspect that the original error was caused by not specifying `"puppet.installType": "pdk"` in the settings, because that's why it used the system ruby.  This will be fixed by https://github.com/lingua-pupuli/puppet-vscode/pull/513.

**Comment by glennsarti** [comment] 2019-05-27 02:26
@synaptis You happy for me to close this?

**Comment by synaptis** [comment] 2019-05-27 03:54
@glennsarti I actually tried to find this over the weekend to request its closure. You could be correct about the root cause (me!) but we have since upgraded to the latest pdk/vscode/extention versions and have found that this issue is no longer present.

Additionally the ability to select the working Puppet version when using the extension with the PDK is excellent, thank you.

Please go ahead and close.

**Comment by glennsarti** [comment] 2019-05-27 04:00
> Additionally the ability to select the working Puppet version when using the extension with the PDK is excellent, thank you.

Our pleasure :-)

**Closed by glennsarti** 2019-05-27 04:00 UTC
